### ISSUE TITLE
Pod doesn't work

### ISSUE THREAD

**Issue by jasonwiener** [malcommac/SwiftSimplify#1]
After installing the pod I tried calling it like I would another pod (say like Alamofire) and the methods were not accessible. It did work, however, if I simply added it to my project.

**Comment by malcommac** [comment]
Hi,
This https://github.com/malcommac/SwiftSimplify/commit/6895533e23dfa84c78296b92c52cca6de5cc773e should solve your problem. Also updated cocoapods spec to 0.1.1.
Let me know.
