### ISSUE TITLE
Tolerance not working as intended?

### ISSUE THREAD

**Issue by sungkim23** [malcommac/SwiftSimplify#9]
Hi all I'm currently using SwiftSimplify to reduce the number of coordinates while running, I'm testing runs that go on for about 1 KM but after using Simplify and giving it about 20 points, all it does is return start and end coordinates.

Simplify is currently like this.
`SwiftSimplify.simplify(self.activityPolyline!, tolerance: 10, highQuality: false)`

Giving it an array of coordinates like this: 
`[(37.330075379999997, -122.02126848), (37.330058049999998, -122.02100589), (37.33000706, -122.02074717000001), (37.329941720000001, -122.02053031), (37.329871330000003, -122.0202987), (37.329823259999998, -122.02006170999999), (37.329705570000002, -122.01986866), (37.329525689999997, -122.01982409), (37.329339840000003, -122.01980544), (37.329133579999997, -122.0197871), (37.328938319999999, -122.01979684), (37.328738469999998, -122.01980584), (37.328532039999999, -122.0198032), (37.32833935, -122.01980995), (37.32814552, -122.01983108), (37.327952580000002, -122.01982651), (37.327758189999997, -122.01980315), (37.327560220000002, -122.01974095), (37.327370989999999, -122.01972170000001), (37.327185819999997, -122.01971872), (37.326979710000003, -122.01972916)]`

After simplify I get this: 
`[(37.330075379999997, -122.02126848), (37.326979710000003, -122.01972916)]`

What am I doing wrong? The location manager is currently configured as follows:
`locationManager.activityType = .fitness`
`locationManager.desiredAccuracy = kCLLocationAccuracyKilometer`
`locationManager.distanceFilter = 20`

Appreciate the help.

**Comment by HubertK** [comment]
Same here. Always returns 1st and last coordinate.

**Comment by Faydee1220** [comment]
I have the same problem, only get two points even tolerance is 0.1

**Comment by freeubi** [comment]
Same problem here, with 0 tolerance i got only 2 points :S

**Comment by koloritcm** [comment]
Related to my issue here: https://github.com/malcommac/SwiftSimplify/issues/7

Your points differ less than 0.01. A tolerance of 10 seems pretty obvious that it would simplify to only two points.

Maybe you are under the assumption that 10 means 10 meters? The tolerance is in the same unit as the input values, so you have a tolerance of 10 degrees of the earth.

You can't use WGS80 coordinates is you want a consistent tolerance as the conversion between degrees latitude/longitude and meters are different for the two dimensions and also changes for different parts of the world

In your case you could convert the points to `MKMapPoint` and then find a suitable `tolerance` by calling `MKMapPointsPerMeterAtLatitude(_:)` and multiply with your tolerance in meters.

**Comment by sungkim23** [comment]
Hey Gunnar! Thanks for the help, actually I ended up getting it to work with the following tolerance of 0.00010, I did further research at the time and noticed it was due to how the coordinates were being interpreted xx.xxxxxx instead of xx.xx
